project_id = "vkcwehaihuoxsmatctex"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_runtime]
enabled = true
ip_version = "ipv4"

[functions.ai-travel-assistant]
verify_jwt = false

[functions.emergency-sos]  
verify_jwt = false

[functions.weather-service]
verify_jwt = false

[functions.file-upload]
verify_jwt = false

[functions.location-tracker]
verify_jwt = false

[functions.email-notifications]
verify_jwt = false

[functions.image-generation]
verify_jwt = false

[functions.document-parser]
verify_jwt = false

[functions.translation-service]
verify_jwt = false

[functions.currency-converter]
verify_jwt = false

[functions.real-time-chat]
verify_jwt = false

[functions.insurance-integration]
verify_jwt = false

[functions.receipt-ocr]
verify_jwt = false

[functions.backup-sync]
verify_jwt = false

[functions.ai-place-recommendations]
verify_jwt = false

[functions.itinerary-generator]
verify_jwt = false

[functions.packing-list-generator]
verify_jwt = false

[functions.trip-analytics]
verify_jwt = false

[functions.local-events-finder]
verify_jwt = false

[functions.document-reminder]
verify_jwt = false

[functions.realtime-emergency]
verify_jwt = false